### ISSUE TITLE
[FEAT] Splash 화면 기능 구현

### ISSUE THREAD

**Issue by arkchive** [Beering-KUIT/Beering-Android#57]
# Description
  Splash 화면 기능 구현 

# TODO
- [x] 불필요한 drawable 파일 및 xml 파일 삭제
- [x] 기존 코드 수정
- [x] SplashActivity.kt
- [x] activity_splash.xml
- [x] AndroidManifest.xml

# ETC
